all: varint sorted_varint_list buffer_pool

varint:
	$(MAKE) -C varint

sorted_varint_list:
	$(MAKE) -C sorted_varint_list

buffer_pool:
	$(MAKE) -C buffer_pool

.PHONY: varint sorted_varint_list buffer_pool

